version: '2.2'
services:

  postgres-liq-demo-local:
    image: postgres:12
    container_name: postgres-liq-demo-local
    restart: on-failure
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      memory: 512
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data

